### ISSUE TITLE
Reporte de Práctica Final de Hilos

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practica-final-de-hilos-equipo-f-g-r#2]
Reporte de Práctica #2 - Práctica Final de Hilos

[Sprint 3 - Reporte de Práctica #2.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-f-g-r/files/6498855/Sprint.3.-.Reporte.de.Practica.2.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Imanol García, Israel Nicolás y Uzias López

**Comment by josealfredo79** [comment]
esta bien hecho...y revisado.
